/* op_search.c - search across folders (port of pstsearch.py).
 *
 * Query syntax (case- and accent-insensitive; all terms must match):
 *   word   "exact phrase"   -word   from:x to:x cc:x subject:x body:x   has:attachment   is:unread|is:read
 *   after:YYYY-MM-DD  before:YYYY-MM-DD   folder:NAME
 * Row level fields come from the contents tables (fast); body terms open each message. */
#include "op_internal.h"
#include "op_foldtab.inc"

/* ---- Unicode folding: casefold(strip_combining(NFKD(c))), table generated by tools/gen_foldtab.py ---------------------- */
static uint32_t dec_cp(const unsigned char **ps, const unsigned char *end) {
    const unsigned char *s = *ps;
    uint32_t c = *s;
    int len = c < 0x80 ? 1 : (c >= 0xC2 && c <= 0xDF) ? 2 : (c >= 0xE0 && c <= 0xEF) ? 3 : (c >= 0xF0 && c <= 0xF4) ? 4 : 0;
    if (len <= 1) { *ps = s + 1; return len ? c : 0xFFFD; }
    if (s + len > end) { *ps = s + 1; return 0xFFFD; }
    c &= (len == 2 ? 0x1Fu : len == 3 ? 0x0Fu : 0x07u);
    for (int k = 1; k < len; k++) {
        if ((s[k] & 0xC0) != 0x80) { *ps = s + 1; return 0xFFFD; }
        c = (c << 6) | (s[k] & 0x3Fu);
    }
    *ps = s + len;
    return c;
}

static const op_fold_ent *fold_lookup(uint32_t cp) {
    size_t lo = 0, hi = sizeof op_fold_ents / sizeof op_fold_ents[0];
    while (lo < hi) {
        size_t mid = (lo + hi) / 2;
        if (op_fold_ents[mid].cp == cp) return &op_fold_ents[mid];
        if (op_fold_ents[mid].cp < cp) lo = mid + 1; else hi = mid;
    }
    return NULL;
}

typedef struct { char *p; size_t n, cap; int bad; } fbuf;
static void fb_cp(fbuf *b, uint32_t cp) {
    if (b->bad) return;
    if (b->n + 5 > b->cap) {
        size_t nc = b->cap ? b->cap * 2 : 128;
        char *t = (char *)realloc(b->p, nc);
        if (!t) { b->bad = 1; return; }
        b->p = t; b->cap = nc;
    }
    char *o = b->p + b->n;
    if (cp < 0x80) *o++ = (char)cp;
    else if (cp < 0x800) { *o++ = (char)(0xC0 | (cp >> 6)); *o++ = (char)(0x80 | (cp & 0x3F)); }
    else if (cp < 0x10000) { *o++ = (char)(0xE0 | (cp >> 12)); *o++ = (char)(0x80 | ((cp >> 6) & 0x3F)); *o++ = (char)(0x80 | (cp & 0x3F)); }
    else { *o++ = (char)(0xF0 | (cp >> 18)); *o++ = (char)(0x80 | ((cp >> 12) & 0x3F)); *o++ = (char)(0x80 | ((cp >> 6) & 0x3F)); *o++ = (char)(0x80 | (cp & 0x3F)); }
    b->n = (size_t)(o - b->p);
}

/* malloc'd folded copy (NUL terminated; length in *outlen); NULL on out of memory */
static char *fold_utf8(const char *s, size_t n, size_t *outlen) {
    fbuf b = {0, 0, 0, 0};
    const unsigned char *p = (const unsigned char *)s, *end = p + n;
    while (p < end) {
        uint32_t c = dec_cp(&p, end);
        if (c < 0x80) { fb_cp(&b, (c >= 'A' && c <= 'Z') ? c + 32 : c); continue; }
        const op_fold_ent *e = fold_lookup(c);
        if (!e) { fb_cp(&b, c); continue; }
        uint32_t off = e->off_len >> 8, len = e->off_len & 0xFF;
        for (uint32_t k = 0; k < len; k++) fb_cp(&b, op_fold_pool[off + k]);
    }
    if (b.bad) { free(b.p); return NULL; }
    if (!b.p) { b.p = (char *)malloc(1); if (!b.p) return NULL; }
    b.p[b.n] = 0;
    if (outlen) *outlen = b.n;
    return b.p;
}

static int fold_contains(const char *hay, size_t hn, const char *needle, size_t nn) {
    if (nn == 0) return 1;
    if (hn < nn) return 0;
    const char *end = hay + hn - nn + 1;
    for (const char *p = hay; p < end; p++) {
        p = (const char *)memchr(p, needle[0], (size_t)(end - p));
        if (!p) return 0;
        if (memcmp(p, needle, nn) == 0) return 1;
    }
    return 0;
}

/* ---- query ------------------------------------------------------------------------------------------------------------- */
enum { F_ANY = 0, F_FROM, F_TO, F_CC, F_SUBJECT, F_BODY };
typedef struct { int field; int neg; char *text; size_t len; } qterm;
typedef struct {
    qterm *t; size_t n, cap;
    int has_att, att;                  /* has:attachment wanted / unwanted */
    int has_unread, unread;
    int has_after, has_before;  int64_t after, before;     /* FILETIME */
    char *folder; size_t folder_len;   /* folded */
    char err[96];
} query;

static void query_free(query *q) {
    for (size_t i = 0; i < q->n; i++) free(q->t[i].text);
    free(q->t); free(q->folder);
    memset(q, 0, sizeof *q);
}

/* shlex.split(posix=True)-like tokenizer; returns number of tokens, -1 on an unbalanced quote / lone backslash */
static int split_posix(const char *s, char ***out) {
    char **v = NULL; size_t nv = 0, cv = 0;
    size_t n = strlen(s);
    char *cur = (char *)malloc(n + 1);
    if (!cur) return -2;
    size_t cl = 0;
    int in_tok = 0, rc = 0;
    for (size_t i = 0; i < n && !rc; i++) {
        char c = s[i];
        if (c == ' ' || c == '\t' || c == '\r' || c == '\n') {
            if (in_tok) {
                cur[cl] = 0;
                if (nv == cv) { cv = cv ? cv * 2 : 8; char **t = (char **)realloc(v, cv * sizeof *t); if (!t) { rc = -2; break; } v = t; }
                v[nv] = (char *)malloc(cl + 1);
                if (!v[nv]) { rc = -2; break; }
                memcpy(v[nv++], cur, cl + 1);
                cl = 0; in_tok = 0;
            }
        } else if (c == '\\') {
            if (i + 1 >= n) { rc = -1; break; }
            cur[cl++] = s[++i]; in_tok = 1;
        } else if (c == '\'') {
            in_tok = 1;
            size_t j = i + 1;
            while (j < n && s[j] != '\'') cur[cl++] = s[j++];
            if (j >= n) { rc = -1; break; }
            i = j;
        } else if (c == '"') {
            in_tok = 1;
            size_t j = i + 1;
            while (j < n && s[j] != '"') {
                if (s[j] == '\\' && j + 1 < n && (s[j + 1] == '"' || s[j + 1] == '\\')) j++;
                cur[cl++] = s[j++];
            }
            if (j >= n) { rc = -1; break; }
            i = j;
        } else { cur[cl++] = c; in_tok = 1; }
    }
    if (!rc && in_tok) {
        cur[cl] = 0;
        if (nv == cv) { cv = cv ? cv * 2 : 8; char **t = (char **)realloc(v, cv * sizeof *t); if (!t) rc = -2; else v = t; }
        if (!rc) { v[nv] = (char *)malloc(cl + 1); if (!v[nv]) rc = -2; else memcpy(v[nv++], cur, cl + 1); }
    }
    free(cur);
    if (rc) { for (size_t i = 0; i < nv; i++) free(v[i]); free(v); return rc; }
    *out = v;
    return (int)nv;
}

/* whitespace split (fallback when quotes do not balance) */
static int split_ws(const char *s, char ***out) {
    char **v = NULL; size_t nv = 0;
    const char *p = s;
    for (;;) {
        while (*p == ' ' || *p == '\t' || *p == '\r' || *p == '\n') p++;
        if (!*p) break;
        const char *e = p;
        while (*e && *e != ' ' && *e != '\t' && *e != '\r' && *e != '\n') e++;
        char **t = (char **)realloc(v, (nv + 1) * sizeof *t);
        if (!t) { for (size_t i = 0; i < nv; i++) free(v[i]); free(v); return -2; }
        v = t;
        v[nv] = (char *)malloc((size_t)(e - p) + 1);
        if (!v[nv]) { for (size_t i = 0; i < nv; i++) free(v[i]); free(v); return -2; }
        memcpy(v[nv], p, (size_t)(e - p)); v[nv++][e - p] = 0;
        p = e;
    }
    *out = v;
    return (int)nv;
}

static int64_t days_from_civil(int64_t y, unsigned m, unsigned d) {
    y -= m <= 2;
    int64_t era = (y >= 0 ? y : y - 399) / 400;
    unsigned yoe = (unsigned)(y - era * 400);
    unsigned doy = (153 * (m > 2 ? m - 3 : m + 9) + 2) / 5 + d - 1;
    unsigned doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
    return era * 146097 + (int64_t)doe - 719468;
}

/* "YYYY-MM-DD" (month / day may have one digit) -> FILETIME of that midnight (UTC); 0 on a bad date */
static int parse_date(const char *s, int64_t *ft) {
    int y = 0, m = 0, d = 0, k = 0;
    for (; k < 4; k++) { if (s[k] < '0' || s[k] > '9') return 0; y = y * 10 + (s[k] - '0'); }
    if (s[k++] != '-') return 0;
    int digits = 0;
    while (s[k] >= '0' && s[k] <= '9' && digits < 2) { m = m * 10 + (s[k++] - '0'); digits++; }
    if (!digits || s[k++] != '-') return 0;
    digits = 0;
    while (s[k] >= '0' && s[k] <= '9' && digits < 2) { d = d * 10 + (s[k++] - '0'); digits++; }
    if (!digits || s[k]) return 0;
    static const int dim[] = {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};
    if (y < 1 || m < 1 || m > 12 || d < 1) return 0;
    int leap = (y % 4 == 0 && y % 100 != 0) || y % 400 == 0;
    if (d > dim[m - 1] + (m == 2 && leap)) return 0;
    *ft = (days_from_civil(y, (unsigned)m, (unsigned)d) * 86400 + 11644473600LL) * 10000000LL;
    return 1;
}

static int ci_eq(const char *a, const char *lit) {
    for (; *lit; a++, lit++) { char c = *a; if (c >= 'A' && c <= 'Z') c = (char)(c + 32); if (c != *lit) return 0; }
    return *a == 0;
}

static int add_term(query *q, int field, int neg, const char *text) {
    size_t fl = 0;
    char *f = fold_utf8(text, strlen(text), &fl);
    if (!f) return OPST_E_NOMEM;
    if (q->n == q->cap) {
        size_t nc = q->cap ? q->cap * 2 : 8;
        qterm *t = (qterm *)realloc(q->t, nc * sizeof *t);
        if (!t) { free(f); return OPST_E_NOMEM; }
        q->t = t; q->cap = nc;
    }
    q->t[q->n].field = field; q->t[q->n].neg = neg; q->t[q->n].text = f; q->t[q->n].len = fl;
    q->n++;
    return 0;
}

static int parse_query(const char *text, query *q) {
    memset(q, 0, sizeof *q);
    /* typographic double quotes count as plain ones */
    size_t n = strlen(text);
    char *norm = (char *)malloc(n + 1);
    if (!norm) return OPST_E_NOMEM;
    size_t o = 0;
    for (size_t i = 0; i < n; i++) {
        if ((unsigned char)text[i] == 0xE2 && (unsigned char)text[i + 1] == 0x80 && ((unsigned char)text[i + 2] == 0x9C || (unsigned char)text[i + 2] == 0x9D)) { norm[o++] = '"'; i += 2; }
        else norm[o++] = text[i];
    }
    norm[o] = 0;
    char **tok = NULL;
    int nt = split_posix(norm, &tok);
    if (nt == -1) nt = split_ws(norm, &tok);
    free(norm);
    if (nt < 0) return OPST_E_NOMEM;
    int rc = 0;
    for (int i = 0; i < nt && !rc; i++) {
        const char *t = tok[i];
        int neg = t[0] == '-' && t[1];
        if (neg) t++;
        const char *colon = strchr(t, ':');
        int key = 0;
        size_t kl = colon ? (size_t)(colon - t) : 0;
        static const char *const keys[] = {"from", "to", "cc", "subject", "body", "has", "is", "after", "before", "folder", NULL};
        if (colon) {
            char kb[16];
            if (kl < sizeof kb) {
                memcpy(kb, t, kl); kb[kl] = 0;
                for (int k = 0; keys[k]; k++) if (ci_eq(kb, keys[k])) { key = k + 1; break; }
            }
        }
        if (key) {
            const char *v = colon + 1;
            if (key == 6) {                                    /* has: */
                if (op_ci_prefix(v, strlen(v), "attach")) { q->has_att = 1; q->att = !neg; }
            } else if (key == 7) {                             /* is: */
                if (ci_eq(v, "unread") || ci_eq(v, "read")) { q->has_unread = 1; q->unread = ci_eq(v, "unread") != neg; }
            } else if (key == 8 || key == 9) {                 /* after: before: */
                int64_t ft;
                if (!parse_date(v, &ft)) snprintf(q->err, sizeof q->err, "bad date \"%.40s\" (use YYYY-MM-DD)", v);
                else if (key == 8) { q->has_after = 1; q->after = ft; }
                else { q->has_before = 1; q->before = ft; }
            } else if (key == 10) {                            /* folder: */
                free(q->folder);
                q->folder = fold_utf8(v, strlen(v), &q->folder_len);
                if (!q->folder) rc = OPST_E_NOMEM;
            } else if (*v) {
                rc = add_term(q, key == 1 ? F_FROM : key == 2 ? F_TO : key == 3 ? F_CC : key == 4 ? F_SUBJECT : F_BODY, neg, v);
            }
        } else if (*t) {
            rc = add_term(q, F_ANY, neg, t);
        }
    }
    for (int i = 0; i < nt; i++) free(tok[i]);
    free(tok);
    if (rc) { query_free(q); return rc; }
    return 0;
}

/* ---- folders --------------------------------------------------------------------------------------------------------- */
typedef struct { uint32_t nid; char *path; int in_deleted; } sfolder;

static int collect_folders(opst *p, uint32_t parent, const char *prefix, int in_del, int depth, sfolder **v, size_t *n, size_t *cap) {
    if (depth > 64) return 0;
    opst_folder_info *kids; size_t nk;
    if (opst_folder_children(p, parent, &kids, &nk) != 0) return 0;
    int rc = 0;
    for (size_t i = 0; i < nk && !rc; i++) {
        size_t pl = strlen(prefix), nl = strlen(kids[i].name);
        char *path = (char *)malloc(pl + nl + 2);
        if (!path) { rc = OPST_E_NOMEM; break; }
        memcpy(path, prefix, pl);
        if (pl) path[pl++] = '/';
        memcpy(path + pl, kids[i].name, nl + 1);
        if (*n == *cap) {
            size_t nc = *cap ? *cap * 2 : 32;
            sfolder *t = (sfolder *)realloc(*v, nc * sizeof **v);
            if (!t) { free(path); rc = OPST_E_NOMEM; break; }
            *v = t; *cap = nc;
        }
        int d = in_del || (p->deleted && kids[i].nid == p->deleted);
        (*v)[*n].nid = kids[i].nid; (*v)[*n].path = path; (*v)[*n].in_deleted = d;
        (*n)++;
        rc = collect_folders(p, kids[i].nid, path, d, depth + 1, v, n, cap);
    }
    opst_free_folders(kids);
    return rc;
}

/* ---- rows ------------------------------------------------------------------------------------------------------------- */
/* text of a contents-table cell, malloc'd (NULL when absent); the Outlook subject prefix is removed */
static char *cell_text(optc *tc, const uint8_t *row, int col, int subject, size_t *len) {
    uint16_t pt; const uint8_t *d; size_t n; void *tf;
    *len = 0;
    if (col < 0 || !op_tc_cell(tc, row, col, &pt, &d, &n, &tf)) return NULL;
    char *s = op_value_to_utf8(pt, d, n, 0, len);
    free(tf);
    if (s && subject && *len >= 2 && (unsigned char)s[0] == 0x01) {
        unsigned char c = (unsigned char)s[1];
        size_t skip = 1 + (c < 0x80 ? 1 : (c & 0xE0) == 0xC0 ? 2 : (c & 0xF0) == 0xE0 ? 3 : (c & 0xF8) == 0xF0 ? 4 : 1);
        if (skip > *len) skip = *len;
        memmove(s, s + skip, *len - skip + 1);
        *len -= skip;
    }
    return s;
}
static int64_t cell_num(optc *tc, const uint8_t *row, int col, int64_t dflt) {
    uint16_t pt; const uint8_t *d; size_t n; void *tf;
    if (col < 0 || !op_tc_cell(tc, row, col, &pt, &d, &n, &tf)) return dflt;
    int64_t v = op_value_i64(pt, d, n, dflt);
    free(tf);
    return v;
}

typedef struct { char *s; size_t n; int done; } lazy;      /* folded field, computed on first use */

typedef struct {
    optc *tc; const uint8_t *row;
    int c_subj, c_from, c_from2, c_to, c_cc;
    lazy subject, sender, to, cc;
} rowctx;

static void lazy_free(lazy *l) { free(l->s); memset(l, 0, sizeof *l); }

static int lazy_fill(rowctx *r, lazy *l, int which, int *oom) {
    if (l->done) return 1;
    l->done = 1;
    size_t n1 = 0, n2 = 0;
    char *a = NULL, *b = NULL;
    switch (which) {
    case 0: a = cell_text(r->tc, r->row, r->c_subj, 1, &n1); break;
    case 1: a = cell_text(r->tc, r->row, r->c_from, 0, &n1); b = cell_text(r->tc, r->row, r->c_from2, 0, &n2); break;
    case 2: a = cell_text(r->tc, r->row, r->c_to, 0, &n1); break;
    default: a = cell_text(r->tc, r->row, r->c_cc, 0, &n1); break;
    }
    size_t tot = n1 + (which == 1 ? 1 + n2 : 0);
    char *joined = (char *)malloc(tot + 1);
    if (!joined) { free(a); free(b); *oom = 1; return 0; }
    if (n1) memcpy(joined, a, n1);
    if (which == 1) { joined[n1] = ' '; if (n2) memcpy(joined + n1 + 1, b, n2); }
    joined[tot] = 0;
    free(a); free(b);
    l->s = fold_utf8(joined, tot, &l->n);
    free(joined);
    if (!l->s) { *oom = 1; return 0; }
    return 1;
}

static int term_in_row(rowctx *r, const qterm *t, int field, int *oom) {
    #define HAS(l, w) (lazy_fill(r, &(l), (w), oom) && fold_contains((l).s, (l).n, t->text, t->len))
    switch (field) {
    case F_SUBJECT: return HAS(r->subject, 0);
    case F_FROM: return HAS(r->sender, 1);
    case F_TO: return HAS(r->to, 2);
    case F_CC: return HAS(r->cc, 3);
    default: return HAS(r->subject, 0) || HAS(r->sender, 1) || HAS(r->to, 2) || HAS(r->cc, 3);
    }
    #undef HAS
}

int opst_search(opst *p, const char *query_utf8, const opst_search_opts *opts, opst_hit **out, size_t *count) {
    if (!p || !query_utf8 || !out || !count) return op_err(OPST_E_ARG, "null argument");
    *out = NULL; *count = 0;
    uint32_t flags = 0, limit = 0;
    const uint32_t *only = NULL; size_t nonly = 0;
    volatile int32_t *cancel = NULL;
    opst_search_progress progress = NULL; void *user = NULL;
    if (opts) {
        if (opts->size < offsetof(opst_search_opts, limit) + sizeof opts->limit) return op_err(OPST_E_ARG, "opst_search_opts.size not set");
        flags = opts->flags; limit = opts->limit;
        if (opts->size >= offsetof(opst_search_opts, user) + sizeof opts->user) {
            only = opts->folders; nonly = opts->nfolders; cancel = opts->cancel; progress = opts->progress; user = opts->user;
        }
    }
    query q;
    int rc = parse_query(query_utf8, &q);
    if (rc) return op_err(rc, "out of memory");
    if (q.err[0]) { rc = op_err(OPST_E_ARG, "%s", q.err); query_free(&q); return rc; }
    int empty = !(q.n || q.has_att || q.has_unread || q.has_after || q.has_before || q.folder);
    int any_unfielded = 0, needs_body_field = 0;
    for (size_t i = 0; i < q.n; i++) { if (q.t[i].field == F_ANY) any_unfielded = 1; if (q.t[i].field == F_BODY) needs_body_field = 1; }
    int need_body = needs_body_field || ((flags & OPST_SEARCH_BODY) && any_unfielded);
    if (empty) { query_free(&q); return 0; }

    sfolder *fl = NULL; size_t nfl = 0, capfl = 0;
    rc = collect_folders(p, OP_NID_ROOT, "", 0, 0, &fl, &nfl, &capfl);
    oplist l = {0};
    if (rc == 0 && op_list_init(&l, sizeof(opst_hit)) != 0) rc = OPST_E_NOMEM;
    if (rc) {
        for (size_t i = 0; i < nfl; i++) free(fl[i].path);
        free(fl); query_free(&q);
        return op_err(OPST_E_NOMEM, "out of memory");
    }
    size_t nhits = 0;
    int oom = 0, stop = 0;
    for (size_t fi = 0; fi < nfl && !stop && !oom; fi++) {
        if (cancel && *cancel) break;
        if ((flags & OPST_SEARCH_SKIP_DELETED) && fl[fi].in_deleted) continue;
        if (nonly) {
            size_t k = 0;
            while (k < nonly && only[k] != fl[fi].nid) k++;
            if (k == nonly) continue;
        }
        if (q.folder) {
            size_t fn = 0;
            char *pf = fold_utf8(fl[fi].path, strlen(fl[fi].path), &fn);
            if (!pf) { oom = 1; break; }
            int ok = fold_contains(pf, fn, q.folder, q.folder_len);
            free(pf);
            if (!ok) continue;
        }
        if (progress) progress(user, fi, nfl, fl[fi].path);
        opnode node; optc tc;
        if (op_node_get(p, (fl[fi].nid & ~0x1Fu) | 0x0E, &node) != 0) continue;
        if (op_tc_open(p, &node, &tc) != 0) continue;
        rowctx rc_;
        memset(&rc_, 0, sizeof rc_);
        rc_.tc = &tc;
        rc_.c_subj = op_tc_col(&tc, 0x0037); rc_.c_from = op_tc_col(&tc, 0x0042); rc_.c_from2 = op_tc_col(&tc, 0x0C1A);
        rc_.c_to = op_tc_col(&tc, 0x0E04); rc_.c_cc = op_tc_col(&tc, 0x0E03);
        int c_sent = op_tc_col(&tc, 0x0039), c_recv = op_tc_col(&tc, 0x0E06), c_flags = op_tc_col(&tc, 0x0E07), c_size = op_tc_col(&tc, 0x0E08);
        size_t path_off = 0;
        for (size_t ri = 0; ri < tc.nrows && !stop && !oom; ri++) {
            if (cancel && *cancel) { stop = 1; break; }
            const uint8_t *row = op_tc_row(&tc, ri);
            if (!row) continue;
            uint32_t mflags = (uint32_t)cell_num(&tc, row, c_flags, 0);
            if (q.has_unread && (!(mflags & 1)) != q.unread) continue;
            if (q.has_att && ((mflags & OPST_MSGFLAG_HASATTACH) != 0) != (q.att != 0)) continue;
            int64_t sent = cell_num(&tc, row, c_sent, 0), recv = cell_num(&tc, row, c_recv, 0);
            if (q.has_after || q.has_before) {
                int64_t d = sent ? sent : recv;
                if (!d) continue;
                if (q.has_after && d < q.after) continue;
                if (q.has_before && d >= q.before) continue;
            }
            rc_.row = row;
            lazy_free(&rc_.subject); lazy_free(&rc_.sender); lazy_free(&rc_.to); lazy_free(&rc_.cc);
            char *body = NULL; size_t body_n = 0; int body_done = 0;
            int ok = 1;
            for (size_t ti = 0; ti < q.n && ok; ti++) {
                const qterm *t = &q.t[ti];
                int found;
                if (t->field == F_BODY || (t->field == F_ANY && need_body && !term_in_row(&rc_, t, F_ANY, &oom))) {
                    if (!body_done) {
                        body_done = 1;
                        opst_msg *m;
                        if (opst_msg_open(p, tc.rowid[ri], &m) == 0) {
                            size_t tl = 0;
                            const char *txt = opst_msg_text(m, &tl);
                            if (txt) { body = fold_utf8(txt, tl, &body_n); if (!body) oom = 1; }
                            opst_msg_close(m);
                        }
                    }
                    found = body && fold_contains(body, body_n, t->text, t->len);
                } else {
                    found = term_in_row(&rc_, t, t->field, &oom);
                }
                if (oom) break;
                if ((found != 0) == (t->neg != 0)) ok = 0;
            }
            free(body);
            if (oom || !ok) continue;
            opst_hit *h = (opst_hit *)op_list_push(&l);
            if (!h) { oom = 1; break; }
            size_t o_subj, o_from, o_to;
            {
                size_t n1; char *s = cell_text(&tc, row, rc_.c_subj, 1, &n1); o_subj = op_list_str(&l, s, n1); free(s);
                s = cell_text(&tc, row, rc_.c_from, 0, &n1);
                if (!s || !n1) { free(s); s = cell_text(&tc, row, rc_.c_from2, 0, &n1); }
                o_from = op_list_str(&l, s, n1); free(s);
                s = cell_text(&tc, row, rc_.c_to, 0, &n1); o_to = op_list_str(&l, s, n1); free(s);
            }
            if (!path_off) path_off = op_list_str(&l, fl[fi].path, strlen(fl[fi].path));
            h = OP_LIST_AT(&l, opst_hit, l.n - 1);              /* the pool may not move elements, but be explicit */
            h->nid = tc.rowid[ri]; h->folder = fl[fi].nid; h->flags = mflags;
            h->sent = sent; h->received = recv; h->size = cell_num(&tc, row, c_size, 0);
            h->has_attachments = (mflags & OPST_MSGFLAG_HASATTACH) != 0;
            h->folder_path = (const char *)(uintptr_t)path_off;
            h->subject = (const char *)(uintptr_t)o_subj; h->sender = (const char *)(uintptr_t)o_from; h->to = (const char *)(uintptr_t)o_to;
            nhits++;
            if (limit && nhits >= limit) stop = 1;
        }
        lazy_free(&rc_.subject); lazy_free(&rc_.sender); lazy_free(&rc_.to); lazy_free(&rc_.cc);
        op_tc_close(&tc);
    }
    for (size_t i = 0; i < nfl; i++) free(fl[i].path);
    free(fl);
    query_free(&q);
    if (oom) { op_list_abort(&l); return op_err(OPST_E_NOMEM, "out of memory"); }
    size_t cnt = l.n;
    for (size_t i = 0; i < cnt; i++) {
        opst_hit *h = OP_LIST_AT(&l, opst_hit, i);
        OP_FIX(&l, h->folder_path); OP_FIX(&l, h->subject); OP_FIX(&l, h->sender); OP_FIX(&l, h->to);
    }
    *out = (opst_hit *)op_list_finish(&l);
    *count = cnt;
    return 0;
}
void opst_free_hits(opst_hit *arr) { op_arr_free(arr); }

/* exposed for tests */
char *op_fold_text(const char *s, size_t n, size_t *outlen) { return fold_utf8(s, n, outlen); }
