using System.ComponentModel;
using System.Diagnostics;

namespace OpenOutlook.Desktop;

/// <summary>Launches only the provider authorization pages generated by DesktopOAuth.</summary>
public static class SystemAuthorizationBrowser
{
    public static async Task LaunchAsync(Uri authorizationUri, CancellationToken cancellationToken)
    {
        Validate(authorizationUri);
        cancellationToken.ThrowIfCancellationRequested();
        try
        {
            var start = new ProcessStartInfo("xdg-open")
            {
                UseShellExecute = false,
                RedirectStandardOutput = true,
                RedirectStandardError = true
            };
            start.ArgumentList.Add(authorizationUri.AbsoluteUri);
            using var process = Process.Start(start) ?? throw new InvalidOperationException();
            using var launchTimeout = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
            launchTimeout.CancelAfter(TimeSpan.FromSeconds(3));
            try
            {
                await process.WaitForExitAsync(launchTimeout.Token).ConfigureAwait(false);
                if (process.ExitCode != 0)
                    throw new InvalidOperationException("Could not launch the authorization browser.");
            }
            catch (OperationCanceledException) when (!cancellationToken.IsCancellationRequested)
            { /* Some desktop openers stay alive after handing the URL to the browser. */ }
        }
        catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested) { throw; }
        catch (Exception exception) when (exception is Win32Exception or InvalidOperationException)
        { throw new InvalidOperationException("Could not launch the authorization browser."); }
    }

    public static void Validate(Uri authorizationUri)
    {
        ArgumentNullException.ThrowIfNull(authorizationUri);
        if (!authorizationUri.IsAbsoluteUri || authorizationUri.Scheme != Uri.UriSchemeHttps ||
            !authorizationUri.IsDefaultPort || authorizationUri.UserInfo.Length != 0 ||
            authorizationUri.Fragment.Length != 0)
            throw new ArgumentException("Invalid authorization page.", nameof(authorizationUri));
        var allowed = authorizationUri.AbsolutePath switch
        {
            "/consumers/oauth2/v2.0/authorize" => authorizationUri.Host == "login.microsoftonline.com",
            "/o/oauth2/v2/auth" => authorizationUri.Host == "accounts.google.com",
            _ => false
        };
        if (!allowed)
            throw new ArgumentException("Invalid authorization page.", nameof(authorizationUri));
    }
}
