#!/usr/bin/env python3
"""Builds the single-file distribution: dist/openpst.c + dist/openpst.h (copy of include/openpst.h).
usage: python3 tools/amalgamate.py   (run from the repository root, or anywhere)
"""
import os, re, sys

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(root, 'src')
order = ['op_platform.c', 'op_util.c', 'op_ndb.c', 'op_inflate.c', 'op_ltp.c', 'op_rtf.c', 'op_search.c', 'op_wr.c', 'op_edit.c', 'op_edit2.c', 'op_ops.c',
         'op_folders.c', 'op_api_w.c', 'op_npm.c', 'op_xcopy.c', 'op_import.c', 'op_fix.c', 'op_check.c', 'op_test.c', 'op_msg.c']
version = open(os.path.join(root, 'include', 'openpst.h')).read()
m = re.search(r'OPST_VERSION_MAJOR (\d+).*?OPST_VERSION_MINOR (\d+).*?OPST_VERSION_PATCH (\d+)', version, re.S)

def read(name):
    return open(os.path.join(src, name), encoding='utf-8').read()

out = ['/* openpst.c - OpenPST %s.%s.%s, single-file distribution (generated by tools/amalgamate.py; do not edit).\n'
       ' * Build:  cc -std=c11 -O2 -c openpst.c      (add -DOPST_SHARED -DOPST_BUILD when building a shared library)\n'
       ' * MIT licensed, no third-party dependencies. API: openpst.h */\n' % m.groups()]
header = read('op_internal.h')
header = re.sub(r'#ifndef OP_INTERNAL_H\n#define OP_INTERNAL_H\n', '', header)
header = re.sub(r'\n#endif\s*$', '\n', header)
out.append('/* ================= internal header ================= */\n' + header)
wr = read('op_wr.h')
wr = wr.replace('#include "op_internal.h"\n', '')
wr = re.sub(r'#ifndef OP_WR_H\n#define OP_WR_H\n', '', wr)
wr = re.sub(r'\n#endif\s*$', '\n', wr)
out.append('/* ================= internal header (writer) ================= */\n' + wr)
for name in order:
    text = read(name)
    text = text.replace('#include "op_internal.h"\n', '').replace('#include "op_wr.h"\n', '')
    for inc in ('op_foldtab.inc', 'op_htmlent.inc'):
        text = text.replace('#include "%s"' % inc, read(inc))
    if '#include "op_mpbb.inc"' in text:
        text = text.replace('#include "op_mpbb.inc"', read('op_mpbb.inc'))
    out.append('\n/* ================= %s ================= */\n%s' % (name, text))
dist = os.path.join(root, 'dist')
os.makedirs(dist, exist_ok=True)
open(os.path.join(dist, 'openpst.c'), 'w', encoding='utf-8', newline='\n').write(''.join(out))
open(os.path.join(dist, 'openpst.h'), 'w', encoding='utf-8', newline='\n').write(version)
print('wrote', os.path.join(dist, 'openpst.c'))
