#!/usr/bin/env python3
"""Generates src/op_foldtab.inc: search folding table = casefold(strip_combining(NFKD(c))) for every code point where that
differs from c (same rule as pstsearch.fold). Combining marks map to nothing. Hangul syllables are left alone.
usage: python3 tools/gen_foldtab.py"""
import os, sys, unicodedata
ents = []
for cp in range(0x80, 0x110000):
    if 0xD800 <= cp < 0xE000 or 0xAC00 <= cp <= 0xD7A3:
        continue
    c = chr(cp)
    d = unicodedata.normalize('NFKD', c)
    d = ''.join(x for x in d if not unicodedata.combining(x)).casefold()
    if d != c:
        ents.append((cp, [ord(x) for x in d]))
pool, rows = [], []
for cp, out in ents:
    rows.append((cp, len(pool), len(out)))
    pool.extend(out)
path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'src', 'op_foldtab.inc')
with open(path, 'w', newline='\n') as f:
    f.write('/* generated by tools/gen_foldtab.py (Unicode %s) - do not edit */\n' % unicodedata.unidata_version)
    f.write('typedef struct { uint32_t cp; uint32_t off_len; } op_fold_ent;      /* off_len = offset << 8 | length */\n')
    f.write('static const op_fold_ent op_fold_ents[%d] = {\n' % len(rows))
    for i in range(0, len(rows), 6):
        f.write(''.join('{0x%X,%d},' % (cp, (off << 8) | n) for cp, off, n in rows[i:i + 6]) + '\n')
    f.write('};\nstatic const uint32_t op_fold_pool[%d] = {\n' % len(pool))
    for i in range(0, len(pool), 12):
        f.write(''.join('0x%X,' % x for x in pool[i:i + 12]) + '\n')
    f.write('};\n')
print(len(rows), 'entries,', len(pool), 'pool;', os.path.getsize(path), 'bytes')
