#!/usr/bin/env python3
"""Generates src/op_htmlent.inc: HTML5 named character references (name without '&' / ';', UTF-8 value, legacy flag =
the name is also valid without the closing ';'). usage: python3 tools/gen_htmlent.py"""
import os, html.entities as H

names = {}
for k, v in H.html5.items():
    legacy = not k.endswith(';')
    n = k.rstrip(';')
    names[n] = (v, names.get(n, (None, False))[1] or legacy)


def cstr(s):
    out = ''
    for b in s.encode('utf-8'):
        # octal escapes always have exactly three digits, so they cannot swallow a following character
        out += '\\%03o' % b if (b >= 0x80 or b < 0x20 or chr(b) in '"\\?') else chr(b)
    return '"' + out + '"'


path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'src', 'op_htmlent.inc')
items = sorted(names.items())
with open(path, 'w', newline='\n') as f:
    f.write('/* generated by tools/gen_htmlent.py - do not edit */\n'
            'typedef struct { const char *name; const char *val; int legacy; } op_htmlent;\n')
    f.write('static const op_htmlent op_htmlents[%d] = {\n' % len(items))
    for n, (v, leg) in items:
        f.write('{"%s",%s,%d},\n' % (n, cstr(v), 1 if leg else 0))
    f.write('};\n')
print(len(items), os.path.getsize(path))
